### ISSUE TITLE
Edit button doesn't appear

### ISSUE THREAD

**Issue by Sunderbraze** [huchenlei/sd-webui-openpose-editor#1]
Able to load the editor from localhost:7680/openpose_editor_index and all features there seem to work as intended, but ControlNet preview won't show the Edit button to call the editor as a pop-in:
![no_edit](https://github.com/huchenlei/sd-webui-openpose-editor/assets/84155151/6f58ac34-1e83-4d8b-8652-97171700f799)

Checked HTML elements to be sure, nothing there, figured the wrapper is missing something

Environment:
-Firefox on Win11
-ControlNet v1.1.202
-Stable-diffusion-webui v1.3.0

Things tried so far:
-MS Edge instead of Firefox
-Light theme instead of dark theme
-Monitor browser console for obvious errors (none that I could see)
-Downgrade ControlNet to 1.1.195 (couldn't find exact v1.1.200 as seen in screenshots)
-Latest npm build (index-43d10c71.css / index-92e8b891.js) instead of package dist v0.0.3 (index-3970bfb1.js / index-e3a1963d.css)

Not too familiar with Vue/Gradio so not sure where to troubleshoot from there

Love the concept though, hope this extension goes far

**Comment by huchenlei** [comment]
Well, sorry for the confusion. 

The integration code on controlnet repo is still being discussed and reviewed. You can follow the thread here:
https://github.com/Mikubill/sd-webui-controlnet/pull/1454

Thanks for the interest in the extension!
For now, you can still use the extension now by typing `localhost:7680/openpose_editor_index` in the browser omibox, and upload JSON file you downloaded from controlnet to do the edit.
