### ISSUE TITLE
button sent to in preprossor window is missing

### ISSUE THREAD

**Issue by JasonKillsUs** [huchenlei/sd-webui-openpose-editor#15]
Greetings, i don´t have  have the buttons in the Preprossesor window to -send it to...
1. downld. as img.png
2. downld. pose.json 
3. close
i checked the dist. folder as mentioned, everything is there, i´m lost

autom.1111 v.1.3.2, phython 3.10.11, torch 2.0.1+cu118, xformers 0.0.17, gradio 3.32.0, checkpoint 33c9f6dfcb

**Comment by huchenlei** [comment]
What controlnet version are you using? The `Edit` button is added on `1.1.216`.

**Comment by JasonKillsUs** [comment]
1.1.108 if tha´s the culprit...i´m updating asap, thanks for the tip

**Comment by JasonKillsUs** [comment]
thanks a ton, that update dit it
