### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mikecastrodemaria** [huchenlei/sd-webui-openpose-editor#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hi, in WebUI I cant find how to get it, no button, no tab, nothing . Sorry but can you tell me how to have access to this dialog interface from controlnet or UI ? Thanks

### Steps to reproduce the problem

1. load the plugin
2. go to txt2img or img2img
3. search the interface ...

### What should have happened?

a tab or a button to access to the openpose

### Commit where the problem happens

Python 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]
Commit hash: 955df7751eef11bb7697e2d77f6b8a6226b21e13

### Command Line Arguments

```Shell
./webui.sh
```

### Console logs

```Shell
nothing to see...
```

### Browser logs

nothing to see...

**Comment by huchenlei** [comment]
See: https://github.com/huchenlei/sd-webui-openpose-editor/discussions/19

There is also a demo video on basic workflow in README.
