### ISSUE TITLE
[Bug] Clicking `edit` for the first time report malformed frame message error

### ISSUE THREAD

**Issue by huchenlei** [huchenlei/sd-webui-openpose-editor#32]
https://www.youtube.com/watch?v=3E5fhFQUVLo&t=2800s
shows the experience installing the extension. 

On the first time clicking the edit button, a bunch of malformed frame message errors are thrown. The editor only becomes usable when close the modal and click on edit again.

**Comment by Jackyutopia** [comment]
谢谢 测试了很多次了 确实可以用了 但是偶尔还是会在更改过程中报错  概率小很多了 这个插件真的很好用 非常感谢 还有一个问题  精确更改每个指节位置如果 作握拳状 有手指遮盖效果的时候还是会出现 手指融合的现象 不置可否后期可以改进一下呢 麻烦啦

**Comment by huchenlei** [comment]
@Jackyutopia 
手指融合的问题其实不是editor能解决的，我试过把画布放得非常大让手部节点完全不互相遮挡去控制也还是会融合。ControlNet是在512x512像素下训练的，openpose骨架图被ControlNet处理的时候就会被压缩导致节点互相覆盖融合，在手在图片中占比不足的时候更为明显。

还有一个问题就是ControlNet的openpose模型在训练的时候训练集里如果也是用同样的preprocessor来处理的话也会有不少手部是没有很好标记的，这也会造成即使用了editor给了ControlNet非常精确的手部骨骼，也还是会生成不符合预期的手部。

**Comment by huchenlei** [comment]
It seems like I cannot reproduce this issue locally, even installing from a fresh checkout of A1111. I added `JSON.stringify` of the frame message in the new version so that from user reports, we might better understand what frame message is being accepted.

**Comment by huchenlei** [comment]
> 您好，我在本地也遇到了类似的报错弹窗，但与视频中不同的是我这边弹窗会一直弹。如您需要一个能复现调试的环境我可以提供帮助，下面是报错详情：
> 
> ```
> Error
> Malformed frame message received: {"source":"VideoTogether","type":16,"data":{"PublicUserId":"354beb10-e010-4474-b556-4cf9a0c6bfb2","MinimiseDefault":true,"DisplayLanguage":"zh-cn","UserscriptType":"Chrome","LoaddingVersion":"1685806209","VideoTogetherTabStorageEnabled":true}}.
> ```

这个感觉是接受了其他来源的frame message。看来可能要考虑遇到没法识别的frame message直接drop掉

**Comment by huchenlei** [comment]
Seems to be fixed by the controlnet side change as people are not reporting it in the past month.
