### ISSUE TITLE
Nothing shows up when click on "edit"

### ISSUE THREAD

**Issue by kendrick0210** [huchenlei/sd-webui-openpose-editor#33]
After installing the extension, there is nothing shows up for edit. The button seems to do nothing. And the buttons layout is also different from yours. The buttons appear below the preview box instead of the right side next to it. No new lines are shown on the cmd when I click on the "edit" button. Please help, thank you.
![openpose editor problem 1](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/9fc13ce7-2f75-4dbb-8511-283f6ebddc1b)
![openpose editor problem 2](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/1e2af1f8-a7fa-4cb7-88d7-22376881407e)

PS: I am able to use it with "http://localhost:7860/openpose_editor_index" and manually upload and download json.

**Comment by huchenlei** [comment]
Can you attach console output both from Browser devtools console and WebUI commandline.

**Comment by kendrick0210** [comment]
![openpose editor problem 4](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/8a8b8aca-ec8f-4068-9393-5426dfb94e94)
![openpose editor problem 5](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/d3c57a2c-8fe3-4988-b4fa-e646811920e3)

**Comment by huchenlei** [comment]
Can you reveal the DOM structure in devtools? Something like this:
![Screenshot (146)](https://github.com/huchenlei/sd-webui-openpose-editor/assets/20929282/9c4e9d63-9131-41ff-ae2c-0e7d7a7fd6ae)

The highlighted element is reported not found in your case according to console output.

**Comment by kendrick0210** [comment]
Sorry, I am not sure how to get to the line you are in. ![openpose editor problem 6](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/c9badb8f-3e0e-4532-b34f-def14fb54fdd)

**Comment by huchenlei** [comment]
Right click on the edit button and select inspect. From there you might want to expand some element to get the state in my screenshot.

**Comment by kendrick0210** [comment]
![openpose editor problem 7](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/e0fb01aa-aafa-4c75-ac00-ef572e9b6a0a)
Look like around here

**Comment by huchenlei** [comment]
Hmmm, it seems more complicated.

Can you put some breakpoints like in this screenshot?
![Screenshot (147)](https://github.com/huchenlei/sd-webui-openpose-editor/assets/20929282/161c234b-3cbb-494a-8fa5-74ba83a5bfc9)

I am interested in whether we get the modal in line15. If that is the case, it means the button is present in the DOM, but the modal is not. 

Try replace the modal.js with following content to see it solves your issue:
```js
const cnetModalRegisteredElements = new Set();
onUiUpdate(() => {
    // Get all the buttons that open a modal
    const btns = gradioApp().querySelectorAll(".cnet-modal-open");

    // Get all the <span> elements that close a modal
    const spans = document.querySelectorAll(".cnet-modal-close");

    // For each button, add a click event listener that opens the corresponding modal
    btns.forEach((btn) => {
        if (cnetModalRegisteredElements.has(btn)) return;
        const modalId = btn.id.replace('cnet-modal-open-', '');
        const modal = document.getElementById("cnet-modal-" + modalId);
        if (!modal) return;
        btn.addEventListener('click', () => {
            modal.style.display = "block";
        });
        cnetModalRegisteredElements.add(btn);
    });

    // For each <span> element, add a click event listener that closes the corresponding modal
    spans.forEach((span) => {
        if (cnetModalRegisteredElements.has(span)) return;
        cnetModalRegisteredElements.add(span);

        const modal = span.parentNode;
        span.addEventListener('click', () => {
            modal.style.display = "none";
        });
    });
});
```

**Comment by kendrick0210** [comment]
Try replace the code. doesn't solve the problem. This is the screenshot.
![openpose editor problem 9](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/cfdc2b74-dd6d-4369-8cce-49e0351594b9)

**Comment by huchenlei** [comment]
So after the code change, it stops complaining that the element is not found?
What is the `modalId` at the breakpoint?

**Comment by kendrick0210** [comment]
The red highlighted error no longer appear in the browser devtools console. I dont know how to get the modalID.... ![openpose editor problem 10](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/8dd45ae6-ef4e-44d1-8187-f23095b505bd)

**Comment by huchenlei** [comment]
Refresh the page with the devtools open. When the execution is paused at line 13, you should see modalId in the Scope panel on the right.

**Comment by kendrick0210** [comment]
![openpose editor problem 11](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/55331624-a5c1-42c2-bc3d-d0a65c235126)

**Comment by huchenlei** [comment]
Strange. As you just checked, modal0 exists, and here the modalId is 0. Does the function returns at line 14?

**Comment by kendrick0210** [comment]
sorry, how do I check it?

**Comment by huchenlei** [comment]
You put a breakpoint at line 14, and see whether modal object is null in the scope panel.

**Comment by kendrick0210** [comment]
![openpose editor problem 12](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/fa4142ca-a1fa-46d6-8527-9d60dde4922a)

**Comment by huchenlei** [comment]
I have no clue why it does not work. In theory if at the time modal is null, next time on UI update, when the modal is present, it will register that callback on the edit button. 

It is also very wield why your buttons are not controlled by the CSS. Do you have other extensions/customizations changing the CSS?

I saw in eariler screenshots the style.css is properly loaded, so it should not be CSS not loading.

**Comment by kendrick0210** [comment]
I tried to disable all other extensions with only the editor and controlnet active but its still not working. It is also weird that the "close" button (I suppose it is a button), i can't even click on it. It is like it is a text string. The cursor doesn't change when it hover over it. The only button seems to be working is just the JSON button.

**Comment by huchenlei** [comment]
So close button also not working under all conditions? That can be really wield as close button's js has been there for a long while.  It is bound using gradio `_js`.

When does this issue start to happen. Is it after a certain ControlNet version? Was the close button working before?

**Comment by kendrick0210** [comment]
![openpose editor problem 13](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/3ffe2a57-3fc3-4480-a3cb-3c1b2d4165b3)
This appears when I try to click the "close" button. Not sure since when it happen. Didn't use much before. But I did try reinstall the both controlnet and editor.

**Comment by kendrick0210** [comment]
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/7ddef3b4-ae26-4588-8309-1d96dcd6b6e3)
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/128599836/5cc1271b-0516-4be7-bf59-0231d6c66449)

**Comment by kendrick0210** [comment]
Hi, after reinstalling everything, including python, stable diffusion and extensions. Now it works perfectly. Thank you for your patience trying to help me out. Thanks.
