### ISSUE TITLE
[Bug]: OpenPose Editor tab missing in webui 1.5.0 

### ISSUE THREAD

**Issue by andreszs** [huchenlei/sd-webui-openpose-editor#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I've downloaded the new [automatic1111 1.5.0 webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.5.0) and setup a new SD installation (because it's safer than trying to update current one), installed this **sd-webui-openpose-editor** and restarted webui, but the **OpenPose Editor** tab is still missing. There's no way to make it show up, the **dist** folder has the proper files, I even re-downloaded them just in case.

![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/10298071/bc0922b7-fe25-41bf-8410-d44f724f9a36)

### Steps to reproduce the problem

1. Install webui 1.5.0 from scratch
2. Install this editor extension
3. Try to locate the OpenPose Editor tab.

### What should have happened?

OpenPose Editor tab should be there.

### Commit where the problem happens

webui: 1.5.0
controlnet: 1.1.233
openpose-editor: Sat Jul 22 21:15:12 2023

### Command Line Arguments

```Shell
set PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
set COMMANDLINE_ARGS=--xformers --no-half --medvram
```

### Console logs

```Shell
venv "C:\stable-diffusion-webui-1.5.0\venv\Scripts\Python.exe"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.0
Commit hash: <none>

Launching Web UI with arguments: --xformers --no-half --medvram
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
2023-07-26 19:15:22,519 - ControlNet - INFO - ControlNet v1.1.233
ControlNet preprocessor location: C:\stable-diffusion-webui-1.5.0\extensions\sd-webui-controlnet\annotator\downloads
2023-07-26 19:15:22,800 - ControlNet - INFO - ControlNet v1.1.233
Loading weights [35d51ba12c] from C:\stable-diffusion-webui-1.5.0\models\Stable-diffusion\kotosAbyssproto_v10.safetensors
Creating model from config: C:\stable-diffusion-webui-1.5.0\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[AgentScheduler] Task queue is empty
[AgentScheduler] Registering APIs
Startup time: 36.0s (launcher: 14.0s, import torch: 6.5s, import gradio: 2.9s, setup paths: 3.4s, other imports: 2.9s, setup codeformer: 0.2s, list SD models: 0.3s, load scripts: 3.1s, create ui: 1.9s, gradio launch: 0.3s, app_started_callback: 0.4s).
Loading VAE weights specified in settings: C:\stable-diffusion-webui-1.5.0\models\VAE\kl-f8-anime2.ckpt
Applying attention optimization: xformers... done.
Model loaded in 59.6s (load weights from disk: 1.7s, create model: 1.3s, apply weights to model: 52.7s, load VAE: 2.1s, load textual inversion embeddings: 0.4s, calculate empty prompt: 1.4s).
```

### Browser logs

XHRGET
http://127.0.0.1:7860/sdapi/v1/sd-models
[HTTP/1.1 404 Not Found 0ms]

XHRGET
http://127.0.0.1:7860/sdapi/v1/samplers
[HTTP/1.1 404 Not Found 0ms]

Uncaught (in promise) TypeError: n.map is not a function
    getSamplers http://127.0.0.1:7860/file=extensions/sd-webui-agent-scheduler/javascript/agent-scheduler.iife.js?1690379297.1120613:302
    promise callback*getSamplers http://127.0.0.1:7860/file=extensions/sd-webui-agent-scheduler/javascript/agent-scheduler.iife.js?1690379297.1120613:302
    <anonymous> http://127.0.0.1:7860/file=extensions/sd-webui-agent-scheduler/javascript/agent-scheduler.iife.js?1690379297.1120613:302
    <anonymous> http://127.0.0.1:7860/file=extensions/sd-webui-agent-scheduler/javascript/agent-scheduler.iife.js?1690379297.1120613:349
agent-scheduler.iife.js:302:3667
Uncaught (in promise) TypeError: n.map is not a function
    getCheckpoints http://127.0.0.1:7860/file=extensions/sd-webui-agent-scheduler/javascript/agent-scheduler.iife.js?1690379297.1120613:302
    promise callback*getCheckpoints http://127.0.0.1:7860/file=extensions/sd-webui-agent-scheduler/javascript/agent-scheduler.iife.js?1690379297.1120613:302
    <anonymous> http://127.0.0.1:7860/file=extensions/sd-webui-agent-scheduler/javascript/agent-scheduler.iife.js?1690379297.1120613:302
    <anonymous> http://127.0.0.1:7860/file=extensions/sd-webui-agent-scheduler/javascript/agent-scheduler.iife.js?1690379297.1120613:349
agent-scheduler.iife.js:302:3764

**Comment by huchenlei** [comment]
See #31 and https://github.com/huchenlei/sd-webui-openpose-editor#usage. The editor is triggered by clicking `edit` button on ControlNet's preprocessor image.
