### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vndroid** [huchenlei/sd-webui-openpose-editor#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

**Describe the bug**
Chrome report 404 error, the path `https://my_stable_diffusion_domain/openpose_editor_index` 

```json
{"detail":"Not Found"}
```

**To Reproduce**

After installation, only.

**Expected behavior**

**Screenshots**
![1690177141403](https://github.com/fkunn1326/openpose-editor/assets/15273693/68ff1cd7-e692-490a-86f8-1ae7818489a2)

**Environment**
 - OS: [e.g. iOS] Windows (Server on Linux x64)
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

### Steps to reproduce the problem

install only

### What should have happened?

work normally

### Commit where the problem happens

webui: 
controlnet:
openpose-editor:

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No
```

### Browser logs

Such as the pic.

**Comment by huchenlei** [comment]
Make sure you have installed the extension properly. ControlNet will send a request to verify if the page exists so 404 is normal if you have not installed the extension.
