### ISSUE TITLE
与插件fkunn1326 / openpose-editor 存在冲突

### ISSUE THREAD

**Issue by kiosty** [huchenlei/sd-webui-openpose-editor#4]
AttributeError: 'Namespace' object has no attribute 'disable_openpose_editor_auto_update'
将openpose-editor插件删除后才能正常使用

**Comment by huchenlei** [comment]
这个问题是没有完全重启webui导致的，因为插件需要一个命令行参数，如果不重启（关闭命令行，网页点击重启不是完全重启）的话preload不会执行。并不是和其他插件有冲突。

**Comment by huchenlei** [comment]
新版本添加了首次安装检测，不会再报这个错了。
