### ISSUE TITLE
Send pose to ControlNet No response

### ISSUE THREAD

**Issue by suaixx** [huchenlei/sd-webui-openpose-editor#41]
I use [ControlNet v1.1.237] to edit the body and press [Send pose to ControlNet] to send it to ControlNet, but it cannot be displayed on ControlNet, only a black screen appears, and sometimes only the edited hands are displayed, but the body cannot show.
But in stable diffusion1.4.1, the above problems did not appear.
stable diffusion 1.5.14
ControlNet v1.1.237
openpose editor 0.1.11

**Comment by huchenlei** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/pull/1913.

Update your ControlNet to latest commit should fix the issue.
