### ISSUE TITLE
Improve Canvas Container

### ISSUE THREAD

**Issue by cenfun** [huchenlei/sd-webui-openpose-editor#42]
Currently, the canvas container is small, sometimes it will be cut off especially edit a portrait, Can we resize the container like following screenshot? Thanks.

![Snipaste_2023-08-27_10-23-12](https://github.com/huchenlei/sd-webui-openpose-editor/assets/334577/f1ad754c-9042-4790-9aa9-7f5d6eda7b6c)

**Comment by huchenlei** [comment]
Done in v0.1.12.

**Comment by cenfun** [comment]
confirm it has been fixed, so quickly thanks
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/334577/ff82f4d3-201e-48a6-bfdd-95904970c29d)
