### ISSUE TITLE
Improve grouping

### ISSUE THREAD

**Issue by cenfun** [huchenlei/sd-webui-openpose-editor#43]
Can we add more groups like left hand/right hand/face, just grouped so that it can be found easily, maybe it doesn't have grouping behavior just grouping, and when the group is collapsed, the scrollbar is smaller. Thanks.

![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/334577/7e22471e-806d-472c-bb7f-70eb6412aae1)

**Comment by huchenlei** [comment]
I don't think it would be better to introduce more nested structure here. From my personal experience, I spend very little time on that list structure. It is only used if I want to know what the keypoint correspond to or I want to make an invisible keypoint visible again.

I would reconsider this if more users report the same issue.
