### ISSUE TITLE
Is it possible to connect hands and wrists?

### ISSUE THREAD

**Issue by cenfun** [huchenlei/sd-webui-openpose-editor#44]
We know that using [DWPose](https://github.com/IDEA-Research/DWPose) can identify the whole body very well including hands
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/334577/cbffc1f9-ce78-4032-9718-67763717bb94)

Unfortunately, when moving the hand, the wrist doesn't follow the hand
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/334577/eb0d1316-a146-42f3-b36a-01306ee6beab)

Is it possible to connect hands and wrists? Thanks
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/334577/ffac6b26-de7b-460d-86ed-9846f0f2c646)

**Comment by huchenlei** [comment]
This feature was originally on the development plan, however, the complexity to make this work was outweighting the benefit it brings so it was not implemented.

Here are some considerations:
- There can only be 1 way binding of body wrist keypoint, i.e. when body wrist keypoint moves, hand wrist keypoint should also move but not vise versa.
- The direction of hand should retain the relative direction to forearm? (Or not change?)
- Whether the size of hand should adjust based on changed forearm size?
- Should the hand be auto-grouped when moving wrist joint?

I will take a look at this when I have time. It is non-trivial on implementation.

**Comment by huchenlei** [comment]
An easier way to achieve this is probably select the whole hand and the wrist joint and move the selected group around. Because this easy workaround exists, I would not consider it worth the engineering effort to implement something more serious.
