### ISSUE TITLE
[Bug]: Openpose editor not found when it is installed and localhost webpage works

### ISSUE THREAD

**Issue by mccalltristan** [huchenlei/sd-webui-openpose-editor#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Openpose editor not found when it is installed and localhost webpage works, 
edit button has strikethrough on controlnet and says
Openpose editor not found. Please make sure you have an openpose editor available on /openpose_editor_index. To hide the edit button, you can check "Disable openpose edit" in Settings.
Following extension(s) provide integration with ControlNet:

   [ huchenlei/sd-webui-openpose-editor](https://github.com/huchenlei/sd-webui-openpose-editor) 

### Steps to reproduce the problem

1. Go to controlnet
2. Press edit
3. a page will pop up saying Openpose editor not found. Please make sure you have an openpose editor available on /openpose_editor_index. To hide the edit button, you can check "Disable openpose edit" in Settings.
Following extension(s) provide integration with ControlNet:

   [ huchenlei/sd-webui-openpose-editor](https://github.com/huchenlei/sd-webui-openpose-editor)

### What should have happened?

it shouldve worked

### Commit where the problem happens

webui: most recent
controlnet: most recent
openpose-editor: most recent

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half --autolaunch --theme dark --no-half-vae --medvram --api
```

### Console logs

```Shell
Launching Web UI with arguments: --opt-sdp-attention --no-half --autolaunch --theme dark --no-half-vae --medvram --api
No module 'xformers'. Proceeding without it.
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[-] ADetailer initialized. version: 23.8.1, num models: 9
2023-08-31 00:10:04,854 - ControlNet - INFO - ControlNet v1.1.313
ControlNet preprocessor location: D:\STABLE\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-08-31 00:10:05,006 - ControlNet - INFO - ControlNet v1.1.313
Loading weights [cca17b08da] from D:\STABLE\stable-diffusion-webui\models\Stable-diffusion\darkSushiMixMix_225D.safetensors
Creating model from config: D:\STABLE\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.3s (launcher: 3.3s, import torch: 3.9s, import gradio: 1.2s, setup paths: 0.8s, other imports: 0.8s, load scripts: 2.9s, initialize extra networks: 0.3s, create ui: 0.5s, gradio launch: 0.4s, app_started_callback: 1.0s).
Applying attention optimization: sdp... done.
Model loaded in 12.9s (load weights from disk: 0.3s, create model: 1.0s, apply weights to model: 11.2s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.2s).
2023-08-31 00:10:37,709 - ControlNet - INFO - Preview Resolution = 512
```

### Browser logs

dont know what this is

### Additional information

windows 11

**Comment by huchenlei** [comment]
Have you tried completely restart of webui from command line?

**Comment by mccalltristan** [comment]
That worked! Thanks, dont know how I didnt try that 💀
