### ISSUE TITLE
The pose cannot be deleted

### ISSUE THREAD

**Issue by mrhanCH** [huchenlei/sd-webui-openpose-editor#46]
Hello, I have successfully installed the plugin and can successfully open the edit box page. The bones can be dragged, but they cannot be deleted using the delete button on the keyboard. How can I solve this problem?
Thanks！

**Comment by huchenlei** [comment]
There is no keyboard keybinding on removing canvas object. You need to click `x` on the left panel to remove skeleton.

![Screen Capture 029 - Openpose Editor - huchenlei github io](https://github.com/huchenlei/sd-webui-openpose-editor/assets/20929282/9281f043-52d8-4564-85af-953118b24c12)

**Comment by mrhanCH** [comment]
Sorry, maybe I expressed the wrong, I mean delete the node, such as after the box, delete the hand node selected by the box, or other nodes.  I hit the delete button and nothing happened.

**Comment by huchenlei** [comment]
You can right click key point to hide it as described in the keybindings section.
