### ISSUE TITLE
预处理后的图片没有显示在画布上

### ISSUE THREAD

**Issue by kiosty** [huchenlei/sd-webui-openpose-editor#5]
云端部署的实例，controlnet处理后的姿态图片和手动上传的json文件都无法在画布上显示，原图有时能在画布上显示，但是比例并不正确，没有错误信息

**Comment by huchenlei** [comment]
请附上截图/复现步骤/webui命令行信息/前端Chrome控制台信息。

**Comment by kiosty** [comment]
![Quicker_20230606_014341](https://github.com/huchenlei/sd-webui-openpose-editor/assets/48428796/fca54579-b9b4-48ed-9bfd-c1ca0218c44d)
![Quicker_20230606_014354](https://github.com/huchenlei/sd-webui-openpose-editor/assets/48428796/5d63b9d2-8b1d-42c8-9cb2-c5c7605acd62)
![Quicker_20230606_014508](https://github.com/huchenlei/sd-webui-openpose-editor/assets/48428796/64f3ff26-0c04-4936-b7c8-47e950844ee3)
部分预处理后的图片在编辑时会抛出这个错误，尝试上传json文件时一直会抛出该错误

**Comment by kiosty** [comment]
> 请附上截图/复现步骤/webui命令行信息/前端Chrome控制台信息。

Webui命令行无任何信息

**Comment by huchenlei** [comment]
能分享一下出现问题的json文件吗？

**Comment by kiosty** [comment]
[poses.zip](https://github.com/huchenlei/sd-webui-openpose-editor/files/11655468/poses.zip)

**Comment by huchenlei** [comment]
应该是因为pose里脸的keypoint数量缺失。正常openpose脸是有70个keypoint的。（每个keypoint是三个数组成），我等下fix一下判断，如果某个身体部分的keypoint缺失应该仍然显示其他正确的部分。
