### ISSUE TITLE
[Bug]: Unable to 3D rotate

### ISSUE THREAD

**Issue by aleph65** [huchenlei/sd-webui-openpose-editor#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hello, love this extension

I am unable to 3d rotate the pose. e.g. if the person is facing directly, I am unable to rotate to make the person face 180 degrees away from the camera instead.

How to achieve this? I am willing to code if required

Thank you

### Steps to reproduce the problem

1. Choose to select a Pose in ControlNet
2. Notice there is no way to rotate the pose on the vertical Z axis or X axis.

### What should have happened?

There should be a way to rotate the pose on vertical Z axis and to also pan the X axis view. We are currently only able to rotate on the Y axis.

### Commit where the problem happens

webui: 
controlnet:
openpose-editor:

### Command Line Arguments

```Shell
default
```

### Console logs

```Shell
default
```

### Browser logs

default

**Comment by huchenlei** [comment]
If you want to obtain the "back" view of a character, you can follow what this youtuber does here:
https://youtu.be/cZO-0yQgQZE?t=1601

**Comment by huchenlei** [comment]
If you are talking about real 3D edit capability, you probably want to look at https://github.com/nonnonstop/sd-webui-3d-open-pose-editor
