### ISSUE TITLE
Enhancement: Mirror Body

### ISSUE THREAD

**Issue by Shanesan** [huchenlei/sd-webui-openpose-editor#51]
Sometimes in odd poses, the body may be calculated by ControlNet to be inverted (the left objects are actually right objects and vice versa, like left shoulder is supposed to be the right shoulder). 

Editing the JSON file to accommodate this is very tricky as the values are not tied to a human-readable variable. Can there be a "Mirror body" option?

**Comment by huchenlei** [comment]
See this video for how to mirror the skeleton:
https://youtu.be/cZO-0yQgQZE?t=1601

**Comment by huchenlei** [comment]
Do you mean the preprocessor result has every pair of left/right keypoints wrong? Can you provide an example? As far as I know, `dw_pose_full` preprocessor is pretty reliable on detecting front/back side.

**Comment by Shanesan** [comment]
Sorry for the delay. That's correct, the preprocessor analyzed that the front was somehow the back (or vice versa) which reversed every bone.

I will have to remember which image I used for processing but when I remember I will add it.

**Comment by huchenlei** [comment]
Got it, so you are requesting adding a button at body level to swap every pair of keypoints all at once?

**Comment by huchenlei** [comment]
Feature implemented in `v0.1.14`.
