### ISSUE TITLE
Is there any way to save it in canvas size?

### ISSUE THREAD

**Issue by kakaruYH03** [huchenlei/sd-webui-openpose-editor#52]
<img width="1540" alt="스크린샷 2023-10-08 123508" src="https://github.com/huchenlei/sd-webui-openpose-editor/assets/54255373/f4067762-64c6-41e0-8496-e05f42eb490f">
<img width="771" alt="스크린샷 2023-10-08 123522" src="https://github.com/huchenlei/sd-webui-openpose-editor/assets/54255373/68f2326c-636a-4cb2-b08a-265fcd4eb61b">

Set the canvas size to 512*768
When you click download
Not only the black background part is saved
Even the gray area outside the background is saved together.
The size of the saved image becomes too large.

Is there a way to save it as "canvas size with black background"?

**Comment by huchenlei** [comment]
Fixed in v0.0.13.
