### ISSUE TITLE
[Bug]: Automatic1111 install fail

### ISSUE THREAD

**Issue by GarmischWg** [huchenlei/sd-webui-openpose-editor#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After installing this openpose editor by pasting the repo link to automatic1111 and restarting the webui, i got the popup saying that the editor is not found.

I have done the following
1. I have checked the dist directory exisit inside the extension's folder
2. Close the browser and terminal and restart
3. press restart ui
4. restart computer
5. verify that "localhost:7860/openpose_editor_index" is accessible, that i can load the editor ui

This happened after i accidentally uninstalled the extension.
This causes me to install the newer version of the extension.

My extension:
controlnet version v1.1.410
![Screenshot 2023-10-15 033249](https://github.com/huchenlei/sd-webui-openpose-editor/assets/43084696/81ec688c-993e-43d5-8cfb-a6df37a1ef80)

### Steps to reproduce the problem

1. Follow these steps: https://github.com/huchenlei/sd-webui-openpose-editor#installation
2. Run a photo through controlnet's openpose processor
3. Click edit in the preview tab

### What should have happened?

The editor should have been shown

### Commit where the problem happens

webui: v1.6.0
controlnet: v1.1.410
openpose-editor: 0.1.13

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--medvram --no-half --xformers --autolaunch
```

### Console logs

```Shell
Already up to date.
venv "D:\ProgramFIles\Stable_Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:29:51) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --medvram --no-half --xformers --autolaunch
No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu117. You might want to consider upgrading.
==============================================================================
You are running torch 1.13.1+cu117.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.19.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
2023-10-15 00:45:15,600 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: D:\ProgramFIles\Stable_Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-10-15 00:45:15,711 - ControlNet - INFO - ControlNet v1.1.410
Loading weights [c6bbc15e32] from D:\ProgramFIles\Stable_Diffusion\stable-diffusion-webui\models\Stable-diffusion\runwayml_v1-5-inpainting.ckpt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.1s (prepare environment: 3.6s, import torch: 2.3s, import gradio: 1.2s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 1.0s, create ui: 0.6s, gradio launch: 0.2s, app_started_callback: 1.9s).
Creating model from config: D:\ProgramFIles\Stable_Diffusion\stable-diffusion-webui\configs\v1-inpainting-inference.yaml
Applying attention optimization: xformers... done.
Model loaded in 6.5s (load weights from disk: 3.3s, create model: 0.3s, apply weights to model: 0.6s, calculate empty prompt: 2.3s).
2023-10-15 00:45:46,985 - ControlNet - INFO - Preview Resolution = 512
```

### Browser logs

Failed to load resource: the server responded with a status of 404 (Not Found) :7860/openpose_editor_index:1
(btw, click the link ":7860/openpose_editor_index:1" works, it launches the editor in another tab)

**Comment by huchenlei** [comment]
I don't think the issue was introduced by `v0.1.13` as it only modifies the logic of `Download Image` button. Can you share a screenshot of the console message of 404?

**Comment by epictetito** [comment]
The same:

webui: v1.6.0
controlnet: v1.1.410
openpose-editor: 0.1.13

It used to work, but at some point it stopped working. I have reinstalled the extension without success

**Comment by GarmischWg** [comment]
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/43084696/ffe78a9a-8b9d-44bf-9b24-0d484ae5df57)

Here is the error message. This message appears without me starting any openpose processing. 

On another note, i haven't undated the extension for at least 1-2 months, so the indeed the version can be any of it. 

Is there a way to specify which commit to install from in Automatic1111?
or is it possible to just use another terminal, cd into the directory and use git command to checkout another commit?

**Comment by huchenlei** [comment]
Ah, I see it is ControlNet extension checking whether the editor is available. 

Can you execute following code in the browser console?
```js
fetch("/openpose_editor_index")
```

If things are normal, you should get something similar to following screenshot:
![Screenshot (181)](https://github.com/huchenlei/sd-webui-openpose-editor/assets/20929282/af834bf2-418f-48b7-aef6-4a240702eda8)

**Comment by GarmischWg** [comment]
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/43084696/5645b358-4f40-470c-8e99-77e9fbfcec1e)

It does seems like everything is ok, but the editor still would not start by clicking the edit button

**Comment by huchenlei** [comment]
I am able to reproduce it now reliably in the page auto-launched by A1111. I think the reason is that the when the page loads, the openpose editor server not ready yet.

**Comment by huchenlei** [comment]
Currently we also have the editor available at https://huchenlei.github.io/sd-webui-openpose-editor/

We might want to fallback onto that address if no local installation is found.

WDYT?

**Comment by GarmischWg** [comment]
Thank you very much, refreashing the page does work.

## SOLUTION
1. Launch the webui normally
2. Refreash the webpage in the browser (Not the UI, not reload UI), you may do so by pressing Ctrl+R on windows Chrome.

**Comment by huchenlei** [comment]
Update your ControlNet extension to `v1.1.411` should fix the issue (No refresh needed).

**Comment by epictetito** [comment]
> Thank you very much, refreashing the page does work.
> 
> ## SOLUTION
> 1. Launch the webui normally
> 2. Refresh the webpage in the browser (Not the UI, not reload UI), you may do so by pressing Ctrl+R on windows Chrome.

Works for me !!
