### ISSUE TITLE
rewrite the key points

### ISSUE THREAD

**Issue by Nomination-NRB** [huchenlei/sd-webui-openpose-editor#55]
Is there a way to use api to rewrite the key points? For example, I uploaded a picture in sd webui controlnet, and the preview effect of the foot key points is not satisfied, can I adjust and move the foot key points through api

**Comment by huchenlei** [comment]
This extension does not provide a Web API.

Currently the ControlNet A1111 extension's `controlnet/detect` API endpoint does return the JSON pose from preprocessor. If you are not satisfied, you can upload that JSON pose file to the editor, do the necessary edit, and save the edited pose image to be used in next API call.

**Comment by Nomination-NRB** [comment]
> This extension does not provide a Web API.
> 
> Currently the ControlNet A1111 extension's API endpoint does return the JSON pose from preprocessor. If you are not satisfied, you can upload that JSON pose file to the editor, do the necessary edit, and save the edited pose image to be used in next API call.`controlnet/detect`

ok, thanks a lot

**Comment by junyuancat1** [comment]
@huchenlei  我也遇到了同样的问题，感谢回答，但我还想问一下我现在已经有了了hand_right_keypoints_2d的pose json，也可以画出pose image，在下一次的API调用中，我应该把这个pose image的内容放在img2img请求的哪一部分来使得openpose使用我给定的pose，而不是自己重新计算pose呢
