### ISSUE TITLE
Please help with a detailed installation procedure

### ISSUE THREAD

**Issue by SAC020** [huchenlei/sd-webui-openpose-editor#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hi,

Not really a bug, I just don't understand how to install this extension. Can you please provide a more detailed installation procedure?

Thank you

### Steps to reproduce the problem

xx

### What should have happened?

xx

### Commit where the problem happens

xx

### Command Line Arguments

```Shell
xx
```

### Console logs

```Shell
xx
```

### Browser logs

xx

**Comment by daswer123** [comment]
First install this extension through install from url , then you need to dowload **dist.zip** in the release, and replace the files inside the folder **dis**t inside the folder of this extension with the replacement files, then everything will work.

**Comment by huchenlei** [comment]
Done. README updated.
