### ISSUE TITLE
[Bug]: What the goal to have a image request on www.photopea.com ?

### ISSUE THREAD

**Issue by ema7569** [huchenlei/sd-webui-openpose-editor#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Your extensions do request on external site www.photopea.com, what the point of that?

### Steps to reproduce the problem

...

### What should have happened?

...

### Commit where the problem happens

webui: 
controlnet:
openpose-editor:

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
...
```

### Console logs

```Shell
...
```

### Browser logs

...

**Comment by huchenlei** [comment]
Photopea edit is part of ControlNet extension feature, which was implemented here: https://github.com/Mikubill/sd-webui-controlnet/pull/2346.

The point of having photopea edit is to help user align multiple preprocessor result images together in a layered fashion.

**Comment by ema7569** [comment]
You really need to download to photopea logo on website each time I launch webui? That called a security breach
