### ISSUE TITLE
Editing actions cannot be synced to contronet

### ISSUE THREAD

**Issue by wangwenqiao666** [huchenlei/sd-webui-openpose-editor#63]
When I generate a pose, And then I clicked the triangle arrow:
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/55267900/e2443680-b2cf-406d-9ca5-02111a349b33)
And then only the first one goes into the contronet:
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/55267900/90b2c8c7-9779-4df2-a606-1876ebe46896)
Here you should click the triangle arrow to automatically jump all the way to controlnet, like this:
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/55267900/4c6ec241-0b97-46da-9bb7-5f37187bb543)
Then I clicked on the Vincennes diagram, only to be the first to enter the controlnet extension:
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/55267900/78c1f121-0b33-43df-a4aa-c32a8bb51d70)
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/55267900/59338cf8-aa97-45ae-9817-9b2d3366bd61)
I wonder if I can add an all-in function here, Thanks!

**Comment by huchenlei** [comment]
Wrong repo. Submit your issue here: https://github.com/nonnonstop/sd-webui-3d-open-pose-editor
