### ISSUE TITLE
[Bug]: The window of openpose-editor is too small

### ISSUE THREAD

**Issue by andrewook** [huchenlei/sd-webui-openpose-editor#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After a clean install i have and edit button but frame of an editor appears shrinked.
![Снимок экрана 2024-01-12 142229](https://github.com/huchenlei/sd-webui-openpose-editor/assets/38736508/ddedeac9-0866-46af-9aa6-b7f0c6cb9ef4)

### Steps to reproduce the problem

***

### What should have happened?

Normaly it should fit to div container.

### Commit where the problem happens

webui: 1.7.0
controlnet: 1.1.430
openpose-editor: 0.2.4

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
***
```

### Browser logs

***

**Comment by andrewook** [comment]
https://github.com/vladmandic/automatic/issues/2594
found relevant issue here for SD.Next, but fix not woeking for automatic1111

**Comment by huchenlei** [comment]
Should be fixed by https://github.com/Mikubill/sd-webui-controlnet/pull/2463
