### ISSUE TITLE
[Bug]: The openpose edit window is not displayed correctly.

### ISSUE THREAD

**Issue by snowsakuraa** [huchenlei/sd-webui-openpose-editor#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The openpose edit window can be used, but the window size is not displayed correctly. Uninstalling and then reinstalling didn't fix it. 
![screenshot20240113](https://github.com/huchenlei/sd-webui-openpose-editor/assets/142369547/fea260cf-a333-4f1c-9c94-fd0c46c09ddf)

### Steps to reproduce the problem

1. Upload an image for processing  
2. Click Edit after processing
3.The window pops up but is displayed at an incorrect size.

### What should have happened?

The window pops up and is displayed at the correct size.

### Commit where the problem happens

webui: 1.7
controlnet:1.1.430
openpose-editor:

### Command Line Arguments

```Shell
Edge
```

### Console logs

```Shell
I haven't seen it.
```

### Browser logs

I haven't seen it.

**Comment by snowsakuraa** [comment]
https://github.com/Mikubill/sd-webui-controlnet/pull/2463/files
A solution has been found. Overwrite the file with the same name in controlnet with this style.css in the link.

**Comment by huchenlei** [comment]
See https://github.com/huchenlei/sd-webui-openpose-editor/issues/64. Duplicated.

**Comment by huchenlei** [comment]
The newest version of ControlNet has this issue fixed.
