### ISSUE TITLE
[Bug]: Page scrolling when space bar is pressed

### ISSUE THREAD

**Issue by Woisek** [huchenlei/sd-webui-openpose-editor#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When the space bar is pressed, the page starts to scroll down. Zooming and panning is not possible.

### Steps to reproduce the problem

1. Press space bar

### What should have happened?

Possibility to zoom and pan

### Commit where the problem happens

webui: SD:next / automatic Version: c0a824d8 Mon Jun 5 10:32:08 2023 -0400
controlnet: v1.1.217
openpose-editor: v0.0.11?

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--listen --insecure --theme=dark --disable-queue
```

### Console logs

```Shell
n/a
```

### Browser logs

n/a

### Additional information

I want to point out, that the model box is not very well implemented. The overflow of the box makes navigating difficult.
The correct way would be to have a page centered box, that adjust itself in height and inside that the iframe with 100% height.

**Comment by huchenlei** [comment]
I am going to reconsider keybinding if at least 1 other user report the same problem with SPACE key.

**Comment by huchenlei** [comment]
> So ... I'm maybe doomed to not be able to use this ... ?! 😧

I suspect it might be related to firefox? I will test it on firefox later today trying to reproduce it. If I cannot reproduce it, I cannot fix it. The fallback would be change the keybinding, which can be a little bit distrubing.

**Comment by Woisek** [comment]
Unfortunately I have no other browser installed. 😔
All I can say, is, that it is a new profile with almost no extensions or ad blockers, stricktly for SD.
The problem with the space bar in web browser is probably the reason, why canvas-zoom did *not* used it and chose another key. 😐

**Comment by huchenlei** [comment]
Bug confirmed on Firefox.

**Comment by huchenlei** [comment]
Will fix on next release.

**Comment by huchenlei** [comment]
Well, the bug not only happens on firefox. It happens on all platforms. If you enter the iframe and directly press space (without doing another other interactions such as click on frame), the browser seems to resend the previous frame message to the iframe, which will cause the editor clear the canvas and redraw everything.

**Comment by huchenlei** [comment]
https://stackoverflow.com/questions/369026/setting-focus-to-iframe-contents
Potential solution. 

Need to fix on ControlNet side.

**Comment by huchenlei** [comment]
Fixed.

**Comment by Woisek** [comment]
Cool! Will check ASAP.

**Comment by huchenlei** [comment]
> 

Are you sure you have the controlnet side patch installed? Need controlnet version 1.1.220+.

Can you share a screenshot of modal overlapping as well?

**Comment by huchenlei** [comment]
> Yes, CN it the latest v1.1.220
> ![Zwischenablagebild (2)](https://user-images.githubusercontent.com/122026301/244384606-f581d029-0d9e-4122-acc5-bc33a0344f73.png)

The UI seems ok in my perspective. Also, when you press space, the iframe scrolls or the main frame a1111 scrolls? Is there a specific sequence of operations to reproduce the scroll?

**Comment by lzwmeng** [comment]
Chinese display error, the text is some symbols

**Comment by huchenlei** [comment]
If you already have the correction in mind, I am happy to merge your PR in ControlNet repo. The modal code is mostly generated by ChatGPT and I stop iterating when the appearnce satisfies my need. 

I guess if I cannot reproduce the issue, I will just add another alt keybinding to panning, make it possible to pan using both SPACE key and F key.

**Comment by huchenlei** [comment]
> Chinese display error, the text is some symbols

Can you submit separate issue and attach some screenshots?

**Comment by huchenlei** [comment]
Pan with key F enabled in v0.0.17. You can try whether key F is working for you now.

**Comment by Woisek** [comment]
Is F + mousewheel scroll used to zoom?

**Comment by huchenlei** [comment]
Modal style fixed in https://github.com/Mikubill/sd-webui-controlnet/pull/1623.

**Comment by Woisek** [comment]
Great! 👍
Is a update sufficient or do we also need to download the dist folder ... ?

**Comment by huchenlei** [comment]
> Great! 👍 Is a update sufficient or do we also need to download the dist folder ... ?

This change is on ControlNet extension so all you need to do is to update the ControlNet extension. So the autoupdate script is not working for you? You can check the version by inspecting `dist/version.txt`. When you update the repo the dist directory will not update. It will be updated when you launch the WebUI. 

If you meet any difficulties on the autoupdate feature (Other than network issue with Github), I would encourage you file a new issue for it.

**Comment by huchenlei** [comment]
BTW, recent updates of the editor solved a major problem in v0.1.0+, which allows you to scale/rotate grouped objects. I strongly encourage you to update if you have not done so.
