### ISSUE TITLE
Chinese display exception

### ISSUE THREAD

**Issue by lzwmeng** [huchenlei/sd-webui-openpose-editor#9]
![QQ截图20230609012402](https://github.com/huchenlei/sd-webui-openpose-editor/assets/109008166/c7179a9d-c319-4316-a793-293c1a22c97e)

**Comment by huchenlei** [comment]
Hmmmm, 跟我预想的不太一样啊；这里是所有非中文的字符乱码了。能分享一下你浏览器的语言设置吗，能附上一些乱码文本就更好了

**Comment by lzwmeng** [comment]
![image](https://github.com/huchenlei/sd-webui-openpose-editor/assets/109008166/f89c35ea-df69-4c13-b634-ce9ce855d4d1)
edge

**Comment by huchenlei** [comment]
能复制一段乱码文本吗？

**Comment by lzwmeng** [comment]
怎么复制？

**Comment by lzwmeng** [comment]
键位绑定
Drag Mouse
Select ungrouped keypoints for rotation/scale/skew
SPACE + Drag Mouse
Hold key to pan the canvas
Mouse wheel
Zoom in/out

**Comment by lzwmeng** [comment]
复制出来是正常的

**Comment by huchenlei** [comment]
我大概了解了，我晚上尝试复现一下，应该是我没设置meta charset的问题，也可能是font-family没有fallback。

**Comment by lzwmeng** [comment]
ok，棒

**Comment by huchenlei** [comment]
我检查了一下我这边meta tag charset是设置成UTF-8的。font-family也有很多fallback。我本地没法复现这个问题，能截一张这样的图吗？
![Screenshot (116)](https://github.com/huchenlei/sd-webui-openpose-editor/assets/20929282/d66bd341-930b-4f67-96e8-cb03830d2426)

**Comment by lzwmeng** [comment]
![搜狗截图20230609114700](https://github.com/huchenlei/sd-webui-openpose-editor/assets/109008166/6cd3aa34-aef1-4903-ad31-eca2f3399ec5)
这样吗

**Comment by huchenlei** [comment]
试试这个solution？
https://www.pconline.com.cn/win10/1126/11261148.html

换其他浏览器也是一样的问题吗？

**Comment by lzwmeng** [comment]
有效，正常了，

**Comment by lzwmeng** [comment]
谢谢，现在汉化很少呀，什么时候可以增加呢，或者自己制作汉化要怎么操作？

**Comment by huchenlei** [comment]
加汉化就是改这个文件：
https://github.com/huchenlei/sd-webui-openpose-editor/blob/main/src/i18n.ts

具体操作可以看这个commit：
f32bb80ebcb8b5f511546b1cf6482e2e42e2f72d

你要是想汉化更多的内容参考上面那个commit交一个Pull Request就行，我觉得没问题就会merge进来。

**Comment by huchenlei** [comment]
如何在github上交一个pull request
ChatGPT
在 GitHub 上提交一个 pull request 通常包括以下步骤：

Fork一个项目： 首先，你需要在GitHub上找到你想要贡献的项目。在项目的右上角，你会看到一个 "Fork" 按钮，点击它，这将会创建一个该项目的副本在你的GitHub账户下。

克隆项目到你的本地系统： 转到你刚才fork的那个项目（应该在你的账户下），点击 "Clone or download" 按钮，复制链接。然后在你的计算机上打开终端，输入 git clone 然后是你复制的链接。

创建一个新的分支： 进入到你刚克隆的项目目录中，使用 git checkout -b [branch-name] 创建一个新的分支。你可以根据你的更改来命名这个分支。

进行更改： 在你的本地系统上进行你想要的更改。

提交更改： 你完成更改后，需要将这些更改添加到你的版本库。首先，使用 git add . 命令将所有更改添加到版本库。然后，使用 git commit -m "your-message" 命令提交这些更改，你的消息应该是对你所做更改的简短描述。

将更改推送到GitHub： 使用 git push origin [branch-name] 将你的更改推送到GitHub。这样，你的更改就会出现在你GitHub上你fork的那个项目的分支里。

提交Pull Request： 转到你的GitHub仓库，点击 "Compare & pull request" 按钮。然后填写一些关于你的更改的详细信息，以便项目所有者了解你的更改意图。当你完成所有信息后，点击 "Create pull request"。

注意：在你提交 Pull Request 前，最好先同步你 Fork 的代码，因为在你 Fork 之后，原始库可能已经有了新的提交。这个步骤可通过以下命令完成：

在本地添加远程原始库： git remote add upstream [原始库git地址]
拉取远程原始库的更新： git fetch upstream
切换到你想同步的分支（一般为master或main）： git checkout master
将远程原始库的更新合并到你的本地： git merge upstream/master
推送更新到你的远程库： git push origin master
只有在你的 Fork 仓库是最新的情况下，你的 Pull Request 才更可能被接受。

以上就是在GitHub上提交Pull Request的一般步骤，如果有任何疑问，请随时向我提问。

**Comment by huchenlei** [comment]
More localization is added in v0.1.2

**Comment by huchenlei** [comment]
你定位到有问题的字体安装之后应该不控制台更改也不会乱码吧
